// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0eIsANrvfVVnLl0iv1itZ2J6sNzOMWK8',
    appId: '1:276991854191:web:8349b60d293bef2c812f9a',
    messagingSenderId: '276991854191',
    projectId: 'bluetalk-23fa9',
    authDomain: 'bluetalk-23fa9.firebaseapp.com',
    storageBucket: 'bluetalk-23fa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2vwj_VyQsyr2El8ku_vrbtbdLa6aL2ho',
    appId: '1:276991854191:android:eca5b4aa6b0f20da812f9a',
    messagingSenderId: '276991854191',
    projectId: 'bluetalk-23fa9',
    storageBucket: 'bluetalk-23fa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdQtAJw8ig1OiLLkXNOQBeJCwAyQ1DKdQ',
    appId: '1:276991854191:ios:4aa30d2daf1d8ef8812f9a',
    messagingSenderId: '276991854191',
    projectId: 'bluetalk-23fa9',
    storageBucket: 'bluetalk-23fa9.firebasestorage.app',
    androidClientId: '276991854191-bnt3ffkjckc4mber8bu4qvrjtfpijv8s.apps.googleusercontent.com',
    iosClientId: '276991854191-d7hr2gbrfkhm365i3f83ik8e5b39eogh.apps.googleusercontent.com',
    iosBundleId: 'com.bluetalk.bluetalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0eIsANrvfVVnLl0iv1itZ2J6sNzOMWK8',
    appId: '1:276991854191:web:f49abc2018e8fd2c812f9a',
    messagingSenderId: '276991854191',
    projectId: 'bluetalk-23fa9',
    authDomain: 'bluetalk-23fa9.firebaseapp.com',
    storageBucket: 'bluetalk-23fa9.firebasestorage.app',
  );
}
